/* The only editable palette is theme/tokens.json. Run npm run theme after changing it. */
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const tokens = JSON.parse(fs.readFileSync(path.join(root, 'theme/tokens.json'), 'utf8'));
const lines = ['// Generated by scripts/build-theme.js. Edit theme/tokens.json instead.'];
Object.entries(tokens).forEach(([group, values]) => {
  if (typeof values !== 'object') return;
  Object.entries(values).forEach(([key, value]) => lines.push(`@${group}-${key}: ${value};`));
});
fs.writeFileSync(path.join(root, 'styles/tokens.less'), `${lines.join('\n')}\n`);
fs.writeFileSync(
  path.join(root, 'config/theme.js'),
  `// Generated from theme/tokens.json\nexport default ${JSON.stringify(tokens, null, 2)};\n`,
);
const icons = {
  check: '<path d="m5 12 4 4L19 6"/>',
  'chat-new': '<path d="M20 11a8 8 0 0 1-8 8H4l-2 3V11a9 9 0 0 1 18 0Z"/><path d="M11 7v8m-4-4h8"/>',
  edit: '<path d="m15.5 4.5 4 4M4 20l4.5-1 12-12a2.83 2.83 0 0 0-4-4l-12 12L4 20Z"/>',
  'ai-search':
    '<path d="M4 6.3 3.8 1.7 8 3.5M12.8 3.5 17 1.7 16.8 6.3"/><circle cx="10.4" cy="11.2" r="8.1"/><path d="m16.2 17 5.6 5.6M6.2 14l2.2-5.5 2.2 5.5m-3.6-1.8h2.8M13.4 8.5V14"/>',

  activity: '<path d="M3 12h4l3-7 4 14 3-7h4"/>',
  cat: '<path d="m5 9-1-6 6 4h4l6-4-1 6a8 8 0 1 1-14 0Z"/><path d="M8 12h.01M16 12h.01m-6 4 2 1 2-1"/>',
  dog: '<path d="m7 5-4 1-1 9 5-3m10-7 4 1 1 9-5-3M7 5h10v11a5 5 0 0 1-10 0Z"/><path d="M10 11h.01M14 11h.01M11 16h2"/>',
  chat: '<path d="M20 11a8 8 0 0 1-8 8H4l-2 3V11a9 9 0 0 1 18 0Z"/><path d="M7 10h8m-8 4h5"/>',
  water: '<path d="M12 3S5 11 5 15a7 7 0 0 0 14 0c0-4-7-12-7-12Z"/>',
  food: '<path d="M3 12h18l-2 8H5zM7 8V5m5 3V3m5 5V5"/>',
  litter: '<path d="M3 12h18l-3 8H6zM6 8h.01M11 6h.01M16 8h.01"/>',
  toy: '<circle cx="12" cy="12" r="9"/><path d="M5 5c8 2 12 6 14 14M19 5C11 7 7 11 5 19M3 12h18M12 3v18"/>',
  device: '<rect x="6" y="3" width="12" height="18" rx="4"/><path d="M10 6h4m-3 12h2"/>',
  settings:
    '<path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="M19.4 13.1a1.5 1.5 0 0 0 .3 1.7l.1.1a1.8 1.8 0 1 1-2.5 2.5l-.1-.1a1.5 1.5 0 0 0-1.7-.3 1.5 1.5 0 0 0-.9 1.4V18.5a1.8 1.8 0 1 1-3.6 0v-.1a1.5 1.5 0 0 0-1-1.4 1.5 1.5 0 0 0-1.7.3l-.1.1a1.8 1.8 0 1 1-2.5-2.5l.1-.1a1.5 1.5 0 0 0 .3-1.7 1.5 1.5 0 0 0-1.4-.9H5.5a1.8 1.8 0 1 1 0-3.6h.1a1.5 1.5 0 0 0 1.4-1 1.5 1.5 0 0 0-.3-1.7l-.1-.1a1.8 1.8 0 1 1 2.5-2.5l.1.1a1.5 1.5 0 0 0 1.7.3h.1a1.5 1.5 0 0 0 .9-1.4V5.5a1.8 1.8 0 1 1 3.6 0v.1a1.5 1.5 0 0 0 .9 1.4 1.5 1.5 0 0 0 1.7-.3l.1-.1a1.8 1.8 0 1 1 2.5 2.5l-.1.1a1.5 1.5 0 0 0-.3 1.7v.1a1.5 1.5 0 0 0 1.4.9h.1a1.8 1.8 0 1 1 0 3.6h-.1a1.5 1.5 0 0 0-1.4.9Z"/>',
  plus: '<path d="M12 5v14M5 12h14"/>',
  back: '<path d="m15 5-7 7 7 7"/>',
  arrow: '<path d="m9 5 7 7-7 7"/>',
  up: '<path d="M12 20V4m-6 6 6-6 6 6"/>',
  close: '<path d="m6 6 12 12M6 18 18 6"/>',
  save: '<path d="M6 3h12v18l-6-4-6 4z"/>',
  saved: '<path fill="COLOR" d="M6 3h12v18l-6-4-6 4z"/>',
  search: '<circle cx="10" cy="10" r="6.5"/><path d="m15 15 5 5"/>',
  post: '<rect x="5" y="3" width="14" height="18" rx="3"/><path d="M9 8h6m-6 4h6m-6 4h3"/>',
  history: '<path d="M3 10a9 9 0 1 1 2 8M3 4v6h6m3-4v6l4 3"/>',
  stop: '<rect x="6" y="6" width="12" height="12" rx="2"/>',
  image:
    '<rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1"/><path d="m4 17 5-5 4 4 3-3 5 5"/>',
};
fs.mkdirSync(path.join(root, 'static/theme'), { recursive: true });
Object.entries(icons).forEach(([name, drawing]) => {
  ['primary', 'muted', 'text', 'inverse', 'accentText'].forEach((tone) => {
    const color = tokens.colors[tone];
    fs.writeFileSync(
      path.join(root, `static/theme/${name}-${tone}.svg`),
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${color}" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${drawing.replace(
        /COLOR/g,
        color,
      )}</svg>`,
    );
  });
});

const appPath = path.join(root, 'app.json');
const app = JSON.parse(fs.readFileSync(appPath, 'utf8'));
app.window.backgroundColor = tokens.colors.page;
app.window.navigationBarBackgroundColor = tokens.colors.page;
app.tabBar.color = tokens.colors.muted;
app.tabBar.selectedColor = tokens.colors.primary;
app.tabBar.backgroundColor = tokens.colors.surface;
fs.writeFileSync(appPath, JSON.stringify(app, null, 2) + '\n');
